name: CI

on:
  push:
    # branches:
    #   - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: ${{ matrix.compiler }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ] # don't bother with windows-latest or macOS-latest
        compiler:
          - dmd-latest
          - ldc-latest
          - dmd-2.106.1 # (released in 2024)
          - dmd-2.105.3 # (released in 2023)
          - dmd-2.104.2 # (released in 2023)
          - dmd-2.103.1 # (released in 2023)
          - dmd-2.102.2 # (released in 2023)
          - dmd-2.101.2 # (released in 2023) ## excluded due to a compiler bug
          - dmd-2.100.2 # (released in 2022) ## GDC 12 can support 2.100
          - dmd-2.099.1 # (released in 2022)
          - dmd-2.098.1 # (released in 2021) ## Has issue re: phobos/std/variant.d
          - dmd-2.097.2 # (released in 2021)

          - ldc-1.35.0 # eq to dmd v2.105.2
          - ldc-1.34.0 # eq to dmd v2.104.2
          - ldc-1.33.0 # eq to dmd v2.103.1
          - ldc-1.28.1 # eq to dmd v2.098.1
          - ldc-1.27.1 # eq to dmd v2.097.2

        # include:
        #   - { os: windows-latest, compiler: dmd-latest }  # Windows Server 2022
        #   - { os: windows-latest, compiler: ldc-latest }  # Windows Server 2022
        #   - { os: macos-latest, compiler: dmd-latest }    # macOS 12 
        #   - { os: macos-latest, compiler: ldc-latest }    # macOS 12

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install D ${{ matrix.compiler }}
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.compiler }}

      # - name: Install dependencies on Ubuntu
      #   if: startsWith(matrix.os, 'ubuntu')
      #   run: sudo apt-get update && sudo apt-get install libgtk-3-dev -y

      # - name: Install dependencies on Mac OSX
      #   if: startsWith(matrix.os, 'mac')
      #   run: brew bundle

      - name: Build All With make
        run: make all

